### ISSUE TITLE
feat: unshare file

### ISSUE THREAD

**Issue by shoriwe** [hawks-atlanta/gateway-java#31]

**Comment by PedroChaparro** [comment]
Hi @SilviaPabon :wave:! We'll create a new release as soon as [medatada-scala/#89](https://github.com/hawks-atlanta/metadata-scala/pull/89) gets merged.

**Comment by SilviaPabon** [comment]
> Hi @SilviaPabon :wave:! We'll create a new release as soon as [medatada-scala/#89](https://github.com/hawks-atlanta/metadata-scala/pull/89) gets merged.

Hi @PedroChaparro 👋 Ok thanks, I will work on it, asap!
