### ISSUE TITLE
fix: delete unnecesary resFileNew variable and replace it with existing ResSession res

### ISSUE THREAD

**Issue by SilviaPabon** [hawks-atlanta/gateway-java#62]
Hello @Woynert I was working on my features 🔨 and azarously 🧙🏻‍♂️ noticed that in the following file from Andres, there is a resFileNew which I think is not necessary, what do you think?

https://github.com/hawks-atlanta/gateway-java/blob/dev/app/src/main/java/gateway/controller/CtrlAuthLogin.java

🤔

**Comment by Woynert** [comment]
Thanks! You are right, fix incoming
