### ISSUE TITLE
📝docs: update the CLI for routes & ports references

### ISSUE THREAD

**Issue by SantiagoGaonaC** [hawks-atlanta/gateway-java#65]
They wrote /api/v1 for the AUTHENTICATION_BASEURL when it should be for METADATA_BASE

**Reference code:**
https://github.com/hawks-atlanta/gateway-java/blob/59506eb2fc4522ba27018f40af730d37402a730f/CLI.md?plain=1#L7-L12
@PedroChaparro

**Comment by Woynert** [comment]
Fixed in https://github.com/hawks-atlanta/gateway-java/commit/f424accb83ca30ce70364c19be432f0b37d90e68
