### ISSUE TITLE
🐛fix: status 204 is sent with content in the body

### ISSUE THREAD

**Issue by SantiagoGaonaC** [hawks-atlanta/gateway-java#67]
Hi, I think the body sending is wrong when using a status 204, in the case of the [ShareFile](https://github.com/hawks-atlanta/gateway-java/blob/main/app/src/main/java/gateway/controller/CtrlShareFile.java#L63) it responds as follows:
```
{
    "response": {
        "return": {
            "code": 204,
            "error": false,
            "msg": "The file have been shared"
        }
    }
}
``` 
## In the code view:
https://github.com/hawks-atlanta/gateway-java/blob/802907582b6b2722a783b5ab6e2ceb032414599e/app/src/main/java/gateway/controller/CtrlShareFile.java#L63

## Ref: 
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
- https://http.cat/status/204

## Note:
This does not directly affect the .NET proxy, as I can adjust it manually, but it would not be an automatic and correct way to handle the statuses depending on the Gateway responses, but it can be considered.

@Woynert @SilviaPabon 💬

**Comment by Woynert** [comment]
Hi! This was made in order to keep consistency between APIs. See [Metadata OpenAPI Spec](https://github.com/hawks-atlanta/metadata-scala/blob/8e5154f458f7fe7780b4f72043ea0cfe848f1a0e/docs/spec.openapi.yaml#L313). This is being done on virtually all implemented endpoints. What do you think?

**Comment by SantiagoGaonaC** [comment]
Ok I understand, from the net proxy we take the Metadata specification, in this case we take the StatusCode 204 and the msg, but according to the http specification we cannot send by body the msg, so we are just going to send the status code to avoid major changes, thanks! 🩹
