### ISSUE TITLE
fix: `file_delete` method is not implemented

### ISSUE THREAD

**Issue by PedroChaparro** [hawks-atlanta/gateway-java#87]
Check the [ServiceImp.java](https://github.com/hawks-atlanta/gateway-java/blob/main/app/src/main/java/gateway/soap/ServiceImp.java) file. It seems that the service is always returning null: 

```java
@WebMethod public ResStatus file_delete (ReqFileDelete args) { return null; }
```

**Comment by Woynert** [comment]
Just noticed :sweat_smile:

**Comment by PedroChaparro** [comment]
Please create a new release once this is fixed so that the proxies can finish implementing this feature
